### ISSUE TITLE
Use websocket instead of interval to update map

### ISSUE THREAD

**Issue by SettingDust** [BlueMap-Minecraft/BlueMapWeb#2]
BlueMapWeb | [BlueMapVue](https://github.com/BlueMap-Minecraft/BlueMapVue/issues/26)

Websocket is far better than so many request

**Comment by TBlueF** [comment]
I added it to the [TODO](https://github.com/BlueMap-Minecraft/BlueMap/projects/1?fullscreen=true), but its **very** low prio right now..

I'll close this issue, since this is very far future, and also affects the whole project, not only Vue and Web :)
